#!/bin/sh

echo "Running ktlint..."
./gradlew ktlintCheck
if [ $? -ne 0 ]; then
  echo "ktlint failed"
  exit 1
fi

echo "Running detekt..."
./gradlew detekt
if [ $? -ne 0 ]; then
  echo "detekt failed"
  exit 1
fi

echo "All checks passed"
exit 0